<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>DanmakuRandomizer</AssemblyName>
    <RootNamespace>DanmakuRandomizer</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="View/**"/>
    <Compile Remove="DanmakuRandomizerPluginTool.cs"/>
    <Compile Remove="Properties/AssemblyInfo.cs"/>
    <Compile Remove="Model/SimpleBullet.cs"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LuaSTGEditorSharp.Core\LuaSTGEditorSharp.Core.csproj"/>
    <ProjectReference Include="..\LuaSTGNode.Legacy\LuaSTGNode.Legacy.csproj"/>
  </ItemGroup>
</Project>
