<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>LuaSTGNode.Legacy</AssemblyName>
    <RootNamespace>LuaSTGEditorSharp</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs"/>
    <Compile Remove="EditorData/Node/Task/ClearTasks.cs"/>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ResourceList/*.json"/>
    <EmbeddedResource Include="images/**/*.png"/>
  </ItemGroup>
  <ItemGroup>
    <Content Include="CustomNodes/*.lua" Link="CustomNodes/%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CustomNodes/Images/**" Link="CustomNodes/Images/%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MoonSharp" Version="2.0.0"/>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LuaSTGEditorSharp.Core\LuaSTGEditorSharp.Core.csproj"/>
  </ItemGroup>
</Project>
